version: 2
updates:
    # Enable version updates
    - package-ecosystem: "npm"
      directories:
          - "/" # Location of package manifests for plugin itself
          - "/samples/*" # Location of package manifests for sample projects
      schedule:
          interval: "weekly"
          day: "monday"
          time: "07:00"
          timezone: "Asia/Tokyo"
      open-pull-requests-limit: 50
      versioning-strategy: increase
    # Keep dependencies for GitHub Actions up-to-date
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "07:00"
          timezone: "Asia/Tokyo"
      labels:
          - "x:size/small"
