version: 2
updates:
    # Enable version updates for plugin itself
    - package-ecosystem: "npm"
      directory: "/" # Location of package manifests
      schedule:
          interval: "monthly"
      open-pull-requests-limit: 50
      versioning-strategy: increase
    # Keep dependencies for GitHub Actions up-to-date
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "monthly"
      labels:
          - "x:size/small"
